name: client_information_example
description: Demonstrates how to use the client_information plugin.
version: 1.0.0

publish_to: 'none'

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  client_information:
    path: ../

  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

dependency_overrides:
  crypto: ^3.0.0

flutter:
  uses-material-design: true
